### ISSUE TITLE
Clear fields in Translator

### ISSUE THREAD

**Issue by espensj** [global-asp/global-asp#12] opened 2016-04-04 18:04 UTC
Can we get a "clear fields" link in Translator to clear the cache? 
Like this:
![clear fields](https://cloud.githubusercontent.com/assets/12679303/14257917/e40b5408-fa54-11e5-9ec7-2056fe601cc1.png)

**Comment by dohliam** [comment] 2016-04-04 18:09
This is a duplicate of [this existing issue](https://github.com/dohliam/gasp-translator/issues/14). Please add further comments there.

(It's a good idea, and I like the idea of putting it in the navigation bar, though I'm still a bit concerned that people (including me :sweat_smile: ) might accidentally erase their work by pressing the button when they didn't mean to. Maybe we could add a confirmation/warning message before erasing. I'll work on it when I have a chance.)

**Closed as completed by dohliam** 2016-04-04 18:09 UTC
